// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT_z-uBtymtKJ_SCg3A70UClufr9dCY_E',
    appId: '1:452646215252:web:9fe142406e46105e2a57c1',
    messagingSenderId: '452646215252',
    projectId: 'fluttertestapp-3f76c',
    authDomain: 'fluttertestapp-3f76c.firebaseapp.com',
    databaseURL: 'https://fluttertestapp-3f76c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttertestapp-3f76c.appspot.com',
    measurementId: 'G-CMMS56V8SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfVJJkHcg56W4WCSU6zCs71N-yA7Ksp9A',
    appId: '1:452646215252:android:73f1adc9dc4ccffa2a57c1',
    messagingSenderId: '452646215252',
    projectId: 'fluttertestapp-3f76c',
    databaseURL: 'https://fluttertestapp-3f76c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttertestapp-3f76c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8_nioZD7vVojE5K1xEcoTWWcv4cF1vDg',
    appId: '1:452646215252:ios:6967db886c045e532a57c1',
    messagingSenderId: '452646215252',
    projectId: 'fluttertestapp-3f76c',
    databaseURL: 'https://fluttertestapp-3f76c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttertestapp-3f76c.appspot.com',
    iosClientId: '452646215252-l41pu5gum2a9c3meui8f7hdd93lgjt90.apps.googleusercontent.com',
    iosBundleId: 'com.testx.testappx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8_nioZD7vVojE5K1xEcoTWWcv4cF1vDg',
    appId: '1:452646215252:ios:7b210c67e13072612a57c1',
    messagingSenderId: '452646215252',
    projectId: 'fluttertestapp-3f76c',
    databaseURL: 'https://fluttertestapp-3f76c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttertestapp-3f76c.appspot.com',
    iosClientId: '452646215252-2svsiqgreni5jqqu4r62sap9tvpvhvms.apps.googleusercontent.com',
    iosBundleId: 'com.testx.testappx.RunnerTests',
  );
}
